#2 extracts exons and joins coding sequnces with their start and stop positions wihtin the genome
dnaopen= open("genomic_dna.txt")
dnaread= dnaopen.read()
exonopen= open("exons.txt")
exonread= exonopen.read()
position= exonread.split(",")
print(str(position))

#['5', '58\n72', '133\n190', '276\n340', '398\n']

print(dnaread[0:6])
#TCGATC
exon1= "TCGATC"
print(dnaread[58:73])
#ACTGATCGATCGATC
exon2="ACTGATCGATCGATC"
print(dnaread[133:191])
#TCGATCATATGTCAGTCGATGCATCGTAGCATCGTATAGTAGCTACGTAGCTACGATC
exon3="TCGATCATATGTCAGTCGATGCATCGTAGCATCGTATAGTAGCTACGTAGCTACGATC"
print(dnaread[276:340])
#GCTAGTACGATCGCGTAGCTAGCATGCTACGTAGATCGATCGATGCATGCTAGCTAGCTAGCTA
exon4="GCTAGTACGATCGCGTAGCTAGCATGCTACGTAGATCGATCGATGCATGCTAGCTAGCTAGCTA"
print(dnaread[398:600])

print(exon1 + exon2 + exon3 + exon4 + exon5)
#TCGATCACTGATCGATCGATCTCGATCATATGTCAGTCGATGCATCGTAGCATCGTATAGTAGCTACGTAGCT#ACGATCGCTAGTACGATCGCGTAGCTAGCATGCTACGTAGATCGATCGATGCATGCTAGCTAGCTAGCTAATG#CTACGTAGATCGATCGCTAGTAGATCGATCGCTAGCTAGCTGACTAGTACGCTGCTAGTAGTCAGCTAGATCG#ATGCTAGTCA

codingdna="TCGATCACTGATCGATCGATCTCGATCATATGTCAGTCGATGCATCGTAGCATCGTATAGTAGCTACGTAGCTACGATCGCTAGTACGATCGCGTAGCTAGCATGCTACGTAGATCGATCGATGCATGCTAGCTAGCTAGCTAATGCTACGTAGATCGATCGCTAGTAGATCGATCGCTAGCTAGCTGACTAGTACGCTGCTAGTAGTCAGCTAGATCGATGCTAGTCA"
